### ISSUE TITLE
Slow?

### ISSUE THREAD

**Issue by RickStrahl** [cwollenhaupt/foxCryptoNG#1]
This is very cool that it can be done without any dependencies but perf of this is very slow compared to .NET based code. Not sure how important that is but it's an order of magnitude slower.

I tried this:

```foxpro
crypt = NEWOBJECT("foxcryptong","foxcryptng.prg")
lcText = "Hello this is a worldly story"
lnIterations = 1000

lnSecs = SECONDS()

FOR lnX = 1 TO lnIterations

crypt.Hash_SHA256(lcText)
lcText = crypt.Hash_SHA512(lcText)

ENDFOR

? TRANSFORM(SECONDS() - lnSecs)
? lcText

DO wwEncryption
LOCAL loE as wwEncryption
loE = CREATEOBJECT("wwEncryption")
loE.Setbinhexmode()

lnSecs = SECONDS()

FOR lnX = 1 TO lnIterations

loE.computehash(lcText,"SHA256")
lcText = loE.computehash(lcText,"SHA512")

ENDFOR

? TRANSFORM(SECONDS() - lnSecs)
? lcText
```

and it takes 15+ seconds for this component, but 0.084 seconds for the wwEncryption code using .NET. I would have thought the API code would be faster.

I suppose it's probably not a big deal and perhaps even a good thing especially when validating hashes to put in some throttling, but I'd rather do that manually than at the base level.

Any thoughts why there's such a drastic difference in perf?

**Comment by cwollenhaupt** [comment]
The API declaration is the slow part. When I move the DeclareApiFunctions call to Init, performance increases from 8.281s to 0.035s on my machine. That is in line with native .NET performance. The drawback is that the function would fail if someone calls CLEAR DLLs between method calls. 

Give the surprising performance difference, I consider that a small price to pay. Thanks, Rick!

**Comment by RickStrahl** [comment]
I should have looked at that - I know that declares are pretty slow. In  Web Connection there are a few critical ones and I make sure they load only once. Didn't think about that here.

Great! This is handy even though I have the .NET ones because no dependencies!

**Comment by cwollenhaupt** [comment]
There's one other difference that might be important. CNG is FIPS 140-2 certified, the managed algorithms in C# are not.

https://csrc.nist.gov/projects/cryptographic-module-validation-program/validated-modules/search

**Comment by RickStrahl** [comment]
I think the FIPS issues is addressed [in .NET 4.8](https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-8/) (search on FIPS). It actually looks like support for this was there already with a flag, but it would fail if the APIs weren't there or disabled. In 4.8 if the APIs are not available it'll fall back to the non-FIPS APIs.
